# Generated by Django 3.2.6 on 2021-08-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
